name: Photos by Drew
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332d28'
    - '#f6fafd'
    - '#726960'
    - '#a5a077'
    - '#c0c8cd'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
