name: Photos by Drew
favicon: null
layout_spectrum: 0.08209772570990026
typography_spectrum: 0.28110601869411767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5159032889641821
  lightness: 0.11283763824030757
  saturation: 0.7674162671901286
  rhythmicContrast: 0.9194695933256298
purpose: []
